// <auto-generated />
using System;
using Microsoft.EntityFrameworkCore;
using Microsoft.EntityFrameworkCore.Infrastructure;
using Microsoft.EntityFrameworkCore.Storage.ValueConversion;
using SmartPlant.API.DbContext;

#nullable disable

namespace SmartPlant.API.Migrations
{
    [DbContext(typeof(PlantContext))]
    partial class PlantContextModelSnapshot : ModelSnapshot
    {
        protected override void BuildModel(ModelBuilder modelBuilder)
        {
#pragma warning disable 612, 618
            modelBuilder
                .HasAnnotation("ProductVersion", "6.0.6")
                .HasAnnotation("Relational:MaxIdentifierLength", 64);

            modelBuilder.Entity("SmartPlant.API.Entities.Moisture", b =>
                {
                    b.Property<int>("MoistureId")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    b.Property<DateTime>("DateTime")
                        .HasColumnType("datetime");

                    b.Property<int>("Percentage")
                        .HasColumnType("int");

                    b.Property<int>("PlantId")
                        .HasColumnType("int");

                    b.HasKey("MoistureId");

                    b.HasIndex("PlantId");

                    b.ToTable("Moistures");

                    b.HasData(
                        new
                        {
                            MoistureId = 1,
                            DateTime = new DateTime(2022, 6, 10, 0, 0, 0, 0, DateTimeKind.Unspecified),
                            Percentage = 58,
                            PlantId = 1
                        },
                        new
                        {
                            MoistureId = 2,
                            DateTime = new DateTime(2022, 6, 11, 0, 0, 0, 0, DateTimeKind.Unspecified),
                            Percentage = 56,
                            PlantId = 1
                        },
                        new
                        {
                            MoistureId = 3,
                            DateTime = new DateTime(2022, 6, 12, 0, 0, 0, 0, DateTimeKind.Unspecified),
                            Percentage = 54,
                            PlantId = 1
                        },
                        new
                        {
                            MoistureId = 4,
                            DateTime = new DateTime(2022, 6, 13, 0, 0, 0, 0, DateTimeKind.Unspecified),
                            Percentage = 52,
                            PlantId = 1
                        },
                        new
                        {
                            MoistureId = 5,
                            DateTime = new DateTime(2022, 6, 14, 0, 0, 0, 0, DateTimeKind.Unspecified),
                            Percentage = 50,
                            PlantId = 1
                        },
                        new
                        {
                            MoistureId = 6,
                            DateTime = new DateTime(2022, 6, 15, 0, 0, 0, 0, DateTimeKind.Unspecified),
                            Percentage = 48,
                            PlantId = 1
                        },
                        new
                        {
                            MoistureId = 7,
                            DateTime = new DateTime(2022, 6, 16, 0, 0, 0, 0, DateTimeKind.Unspecified),
                            Percentage = 46,
                            PlantId = 1
                        },
                        new
                        {
                            MoistureId = 8,
                            DateTime = new DateTime(2022, 6, 17, 0, 0, 0, 0, DateTimeKind.Unspecified),
                            Percentage = 44,
                            PlantId = 1
                        },
                        new
                        {
                            MoistureId = 9,
                            DateTime = new DateTime(2022, 6, 10, 0, 0, 0, 0, DateTimeKind.Unspecified),
                            Percentage = 58,
                            PlantId = 2
                        },
                        new
                        {
                            MoistureId = 10,
                            DateTime = new DateTime(2022, 6, 11, 0, 0, 0, 0, DateTimeKind.Unspecified),
                            Percentage = 56,
                            PlantId = 2
                        },
                        new
                        {
                            MoistureId = 11,
                            DateTime = new DateTime(2022, 6, 12, 0, 0, 0, 0, DateTimeKind.Unspecified),
                            Percentage = 54,
                            PlantId = 2
                        },
                        new
                        {
                            MoistureId = 12,
                            DateTime = new DateTime(2022, 6, 13, 0, 0, 0, 0, DateTimeKind.Unspecified),
                            Percentage = 52,
                            PlantId = 2
                        },
                        new
                        {
                            MoistureId = 13,
                            DateTime = new DateTime(2022, 6, 14, 0, 0, 0, 0, DateTimeKind.Unspecified),
                            Percentage = 50,
                            PlantId = 2
                        },
                        new
                        {
                            MoistureId = 14,
                            DateTime = new DateTime(2022, 6, 15, 0, 0, 0, 0, DateTimeKind.Unspecified),
                            Percentage = 48,
                            PlantId = 2
                        },
                        new
                        {
                            MoistureId = 15,
                            DateTime = new DateTime(2022, 6, 16, 0, 0, 0, 0, DateTimeKind.Unspecified),
                            Percentage = 46,
                            PlantId = 2
                        },
                        new
                        {
                            MoistureId = 16,
                            DateTime = new DateTime(2022, 6, 17, 0, 0, 0, 0, DateTimeKind.Unspecified),
                            Percentage = 44,
                            PlantId = 2
                        });
                });

            modelBuilder.Entity("SmartPlant.API.Entities.Plant", b =>
                {
                    b.Property<int>("PlantId")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    b.Property<int>("MaxMoistureLevel")
                        .HasColumnType("int");

                    b.Property<int>("MaxWaterLevel")
                        .HasColumnType("int");

                    b.Property<int>("MinMoistureLevel")
                        .HasColumnType("int");

                    b.Property<int>("MinWaterLevel")
                        .HasColumnType("int");

                    b.Property<string>("Name")
                        .IsRequired()
                        .HasMaxLength(50)
                        .HasColumnType("varchar(50)");

                    b.HasKey("PlantId");

                    b.ToTable("Plants");

                    b.HasData(
                        new
                        {
                            PlantId = 1,
                            MaxMoistureLevel = 0,
                            MaxWaterLevel = 0,
                            MinMoistureLevel = 0,
                            MinWaterLevel = 0,
                            Name = "Alocasia"
                        },
                        new
                        {
                            PlantId = 2,
                            MaxMoistureLevel = 0,
                            MaxWaterLevel = 0,
                            MinMoistureLevel = 0,
                            MinWaterLevel = 0,
                            Name = "Bonsai"
                        },
                        new
                        {
                            PlantId = 3,
                            MaxMoistureLevel = 0,
                            MaxWaterLevel = 0,
                            MinMoistureLevel = 0,
                            MinWaterLevel = 0,
                            Name = "Cactus"
                        },
                        new
                        {
                            PlantId = 4,
                            MaxMoistureLevel = 0,
                            MaxWaterLevel = 0,
                            MinMoistureLevel = 0,
                            MinWaterLevel = 0,
                            Name = "Palmboom"
                        });
                });

            modelBuilder.Entity("SmartPlant.API.Entities.WaterLevel", b =>
                {
                    b.Property<int>("WaterLevelId")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    b.Property<DateTime>("DateTime")
                        .HasColumnType("datetime");

                    b.Property<int>("Percentage")
                        .HasColumnType("int");

                    b.Property<int>("PlantId")
                        .HasColumnType("int");

                    b.HasKey("WaterLevelId");

                    b.HasIndex("PlantId");

                    b.ToTable("WaterLevels");

                    b.HasData(
                        new
                        {
                            WaterLevelId = 1,
                            DateTime = new DateTime(2022, 6, 10, 0, 0, 0, 0, DateTimeKind.Unspecified),
                            Percentage = 58,
                            PlantId = 1
                        },
                        new
                        {
                            WaterLevelId = 2,
                            DateTime = new DateTime(2022, 6, 11, 0, 0, 0, 0, DateTimeKind.Unspecified),
                            Percentage = 56,
                            PlantId = 1
                        },
                        new
                        {
                            WaterLevelId = 3,
                            DateTime = new DateTime(2022, 6, 12, 0, 0, 0, 0, DateTimeKind.Unspecified),
                            Percentage = 54,
                            PlantId = 1
                        },
                        new
                        {
                            WaterLevelId = 4,
                            DateTime = new DateTime(2022, 6, 13, 0, 0, 0, 0, DateTimeKind.Unspecified),
                            Percentage = 52,
                            PlantId = 1
                        },
                        new
                        {
                            WaterLevelId = 5,
                            DateTime = new DateTime(2022, 6, 14, 0, 0, 0, 0, DateTimeKind.Unspecified),
                            Percentage = 50,
                            PlantId = 1
                        },
                        new
                        {
                            WaterLevelId = 6,
                            DateTime = new DateTime(2022, 6, 15, 0, 0, 0, 0, DateTimeKind.Unspecified),
                            Percentage = 48,
                            PlantId = 1
                        },
                        new
                        {
                            WaterLevelId = 7,
                            DateTime = new DateTime(2022, 6, 16, 0, 0, 0, 0, DateTimeKind.Unspecified),
                            Percentage = 46,
                            PlantId = 1
                        },
                        new
                        {
                            WaterLevelId = 8,
                            DateTime = new DateTime(2022, 6, 17, 0, 0, 0, 0, DateTimeKind.Unspecified),
                            Percentage = 44,
                            PlantId = 1
                        },
                        new
                        {
                            WaterLevelId = 9,
                            DateTime = new DateTime(2022, 6, 10, 0, 0, 0, 0, DateTimeKind.Unspecified),
                            Percentage = 38,
                            PlantId = 2
                        },
                        new
                        {
                            WaterLevelId = 10,
                            DateTime = new DateTime(2022, 6, 11, 0, 0, 0, 0, DateTimeKind.Unspecified),
                            Percentage = 36,
                            PlantId = 2
                        },
                        new
                        {
                            WaterLevelId = 11,
                            DateTime = new DateTime(2022, 6, 12, 0, 0, 0, 0, DateTimeKind.Unspecified),
                            Percentage = 34,
                            PlantId = 2
                        },
                        new
                        {
                            WaterLevelId = 12,
                            DateTime = new DateTime(2022, 6, 13, 0, 0, 0, 0, DateTimeKind.Unspecified),
                            Percentage = 32,
                            PlantId = 2
                        },
                        new
                        {
                            WaterLevelId = 13,
                            DateTime = new DateTime(2022, 6, 14, 0, 0, 0, 0, DateTimeKind.Unspecified),
                            Percentage = 30,
                            PlantId = 2
                        },
                        new
                        {
                            WaterLevelId = 14,
                            DateTime = new DateTime(2022, 6, 15, 0, 0, 0, 0, DateTimeKind.Unspecified),
                            Percentage = 28,
                            PlantId = 2
                        },
                        new
                        {
                            WaterLevelId = 15,
                            DateTime = new DateTime(2022, 6, 16, 0, 0, 0, 0, DateTimeKind.Unspecified),
                            Percentage = 26,
                            PlantId = 2
                        },
                        new
                        {
                            WaterLevelId = 16,
                            DateTime = new DateTime(2022, 6, 17, 0, 0, 0, 0, DateTimeKind.Unspecified),
                            Percentage = 24,
                            PlantId = 2
                        });
                });

            modelBuilder.Entity("SmartPlant.API.Entities.Moisture", b =>
                {
                    b.HasOne("SmartPlant.API.Entities.Plant", "Plant")
                        .WithMany("MoistureLevels")
                        .HasForeignKey("PlantId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("Plant");
                });

            modelBuilder.Entity("SmartPlant.API.Entities.WaterLevel", b =>
                {
                    b.HasOne("SmartPlant.API.Entities.Plant", "Plant")
                        .WithMany("WaterLevels")
                        .HasForeignKey("PlantId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("Plant");
                });

            modelBuilder.Entity("SmartPlant.API.Entities.Plant", b =>
                {
                    b.Navigation("MoistureLevels");

                    b.Navigation("WaterLevels");
                });
#pragma warning restore 612, 618
        }
    }
}
